[package]
name = "reverse-proxy-rust"
version = "0.1.0"
authors = ["Adrien Bonnivard"]
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
